@endpoint=http://localhost:3000

POST {{ endpoint }}/login
Content-Type: application/json

{
  "email":"romuald.patfoort@gmail.com",
  "password": "chaton123"
}

###
POST {{ endpoint }}/login
Content-Type: application/json

{
  "email":"jean.dujardin@mail.io",
  "password": "yjjk8E676a9JQZ"
}


###
PATCH {{endpoint}}/player/1
Content-Type: application/json

{
  
}