@endpoint=http://localhost:3000

POST {{ endpoint }}/login
Content-Type: application/json
git 
{
  "email":"jean.dujardin@mail.io",
  "password": "yjjk8E676a9JQZ!",
  "role": "joueur"
}

###
POST {{ endpoint }}/login
Content-Type: application/json

{
  "email":"rp@mail.io",
  "password": "Test123!",
  "role" : "joueur"
}

###
POST {{ endpoint }}/register
Content-Type: application/json

{
  "firstname":"Romuald",
  "lastname":"Patfoort",
  "email":"rp@mail.io",
  "password": "Test123!", 
  "confirmedPassword": "Test123!", 
  "role": "joueur"
}


###
POST {{ endpoint }}/register/joueur
Content-Type: application/json

{
  "id": 21,
  "email": "rp@mail.io",
  "role": "joueur",
  "birth_date": "1990-06-12",
  "nationality": "Français",
  "genre": "Homme",
  "height": 184,
  "weight": 61,
  "strong_foot": "Droit",
  "position": "Attaquant"
}

###
POST {{ endpoint }}/register
Content-Type: application/json

{
  "firstname":"Romuald",
  "lastname":"Patfoort",
  "email":"rp2@mail.io",
  "password": "Test123!", 
  "confirmedPassword": "Test123!", 
  "role": "recruteur"
}

###
POST {{ endpoint }}/register/recruteur
Content-Type: application/json

{
  "id": 22,
  "email": "rp2@mail.io",
  "role": "recruteur",
  "city": "St Ouen sur Seine",
  "club": "Red Star"
}


###
GET {{endpoint}}/player/1/match/2/stats

###
PATCH {{endpoint}}/player/1
Content-Type: application/json

{
  "height": 210,
  "weight": 120
}

###
GET {{endpoint}}/player/1/match

###
GET {{endpoint}}/scout/4/player/1/stats

###
DELETE {{endpoint}}/scout/4/player/1

###
GET {{endpoint}}/scout/2/player/1

###
PATCH {{endpoint}}/scout/4
Content-Type: application/json

{
  "firstname": "Jean Jacques",
  "lastname": "Dujardin"
}

###
GET {{endpoint}}/player/5

###
POST {{endpoint}}/player/1/match
Content-Type: application/json

{
  "homeTeam": 1,
  "awayTeam": 2
}


###
PATCH {{endpoint}}/player/1/match/3
Content-Type: application/json

{
  "score": "10-10"
}
###
GET {{ endpoint }}/scout/2/player/1

###
GET {{ endpoint }}/scout/2/player/1/match/2/stats

###
GET {{ endpoint }}/scout/search/?strong_foot=gauche&position=Gardien

###
GET {{endpoint}}/datas/teams
